# Generated by Django 5.1.5 on 2025-03-23 09:22

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('original_file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg'])])),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='duration of the video')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('processing_log', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('unlisted', 'Unlisted')], default='private', max_length=10)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('aspect_ratio', models.CharField(blank=True, max_length=20)),
                ('framerate', models.PositiveIntegerField(blank=True, null=True)),
                ('filesize', models.BigIntegerField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('2160p', '4K'), ('1440p', '2K'), ('1080p', 'HD'), ('720p', 'HD Ready'), ('480p', 'SD')], max_length=10)),
                ('file', models.FileField(upload_to='videos/processed/')),
                ('bitrate', models.CharField(max_length=20)),
                ('codec', models.CharField(max_length=10)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='thumbnails/')),
                ('size', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='videos.video')),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['uploader', 'visibility'], name='videos_vide_uploade_e066f2_idx'),
        ),
    ]
